/* GPT-012: three permanent private retail identities and three optional T502 themes.
   Embedded in the native game IIFE. No new workers, shipping, food conversion or income engine. */
const RIVERSIDE012=Object.freeze({
  278:Object.freeze({k:278,id:'riversideArcade012',nm:'英式河畔拱廊市場',en:'British riverside arcade market',ic:'🏪',sz:3,cost:3200,rank:6,cat:'civic',kind:'C',jobs:18,power:3.5,water:3.5}),
  279:Object.freeze({k:279,id:'flowerStall012',nm:'英式河畔花卉攤',en:'British riverside flower stall',ic:'💐',sz:1,cost:380,rank:3,cat:'civic',kind:'C',jobs:3,power:.5,water:.6}),
  280:Object.freeze({k:280,id:'produceStall012',nm:'英式河畔蔬果攤',en:'British riverside produce stall',ic:'🥕',sz:1,cost:420,rank:3,cat:'civic',kind:'C',jobs:4,power:.6,water:.9})
});
const RIVERSIDE_TOOL012=Object.freeze(Object.fromEntries(Object.values(RIVERSIDE012).map(q=>[q.id,q])));
const RIVERSIDE_PATH012=Object.freeze({
  riverQuay012:Object.freeze({id:'riverQuay012',nm:'英式石砌岸沿步道',en:'British stone quay paving',ic:'🧱',sz:1,rank:4,theme:'quay'}),
  riverRail012:Object.freeze({id:'riverRail012',nm:'英式鐵欄河畔步道',en:'British iron-railing riverside paving',ic:'🌉',sz:1,rank:4,theme:'rail'}),
  riverPromenade012:Object.freeze({id:'riverPromenade012',nm:'英式河畔散步道',en:'British river promenade paving',ic:'🚶',sz:1,rank:4,theme:'promenade'})
});
let riversideArtCanonical012=null;
function riversideKind012(k){return Object.prototype.hasOwnProperty.call(RIVERSIDE012,k);}
function riversideBuilt012(b){return !!(b&&!b.ref&&riversideKind012(b.k)&&b.age>=9);}
function riversideOperational012(root,b){return !!(riversideBuilt012(b)&&b.pw&&b.wa&&!powerLegacy450()&&!waterLegacy449()&&POWER_ROOT_OK471[root]===1&&WATER_ROOT_STATE472[root]>=2&&WATER_ROOT_DELIVERED472[root]>0&&britishRoad004(root)&&!b.fire&&!b.sick&&!b.death&&!b.abandoned&&!b.riot&&!b.plague&&assetAvailability493(root,'services')>.02);}
function riversideWaterFactor012(root,b){if(!riversideOperational012(root,b))return 0;const demand=rootWaterDemandBase472(b)*waterProfile472(b)[1]*waterPolicyDemandMul472(b);return demand>0?clamp(WATER_ROOT_DELIVERED472[root]/demand,0,1):0;}
function refreshRiversideUtilities012(){for(const root of tickBld||[]){const b=tiles[root]?.bld;if(!b||b.ref||!riversideKind012(b.k))continue;b.pw=!!(!powerLegacy450()&&POWER_ROOT_OK471[root]===1);b.wa=!!(b.pw&&!waterLegacy449()&&WATER_ROOT_STATE472[root]>=2&&WATER_ROOT_DELIVERED472[root]>0);}}
function riversideRetailUnits012(){let n=0;for(const root of tickBld||[]){const b=tiles[root]?.bld;if(!b||b.ref||!riversideKind012(b.k)||!riversideOperational012(root,b))continue;const e=enterpriseRootInfo489(root);if(e?.k===b.k)n+=Math.max(0,e.employed||0)/JOBSC[2];}return n;}
// Pure placement-time visual orientation. Canonical quay edge is east (x=16).
// Preserve this turn in native optional theme metadata; moving the camera or
// changing later terrain never rewrites a saved path or creates shore capacity.
function riversideShoreTurn012(x,y){for(let d=1;d<=4;d++)for(const [dx,dy,turn]of[[0,1,1],[-1,0,2],[0,-1,3],[1,0,0]]){const a=x+dx*d,b=y+dy*d;if(inMap(a,b)&&tiles[idx(a,b)]?.t===0)return turn;}return 0;}
function riversideTheme012(t){const theme=t?.amx502?.british012;return t?.am502===1&&['quay','rail','promenade'].includes(theme)?theme:null;}
function riversideDescription012(q){if(q.theme)return '獨立付費原生陸上步道，步行成本 0.72；'+q.nm+'為可拆除的視覺主題。鐵欄不是鐵路，岸沿不是港口；無額外航運、觀光、職位或公共服務。';return q.sz+'×'+q.sz+' 固定英式零售建築，九天竣工後需真正臨路、實際供電與送達的水。'+q.jobs+' 名目私營職位，實際聘用由既有企業／景氣／通勤系統決定。購物與商業稅依實際供貨、營運與聘用結算；無額外食物轉換、觀光或市政維護費。'+(q.sz===3?'開放庭院屬於整座建築地塊，不能另鋪步道或擺攤。':'');}
function riversideInspect012(root,b){const q=RIVERSIDE012[b.k],on=riversideOperational012(root,b),e=enterpriseRootInfo489(root),same=e?.k===b.k;return '<h3>'+q.ic+' '+q.nm+'</h3><div class="row">'+q.en+'</div><div class="row">'+(b.age<9?'施工中 '+Math.floor(b.age)+'/9 天':on?'營運基建就緒':'離線：需道路、供電與供水')+'</div><div class="row">名目私營職位 '+q.jobs+'｜有效 '+(on&&same?e.activePositions||0:0)+'｜實際聘用 '+(on&&same?e.employed||0:0)+'</div><div class="row">'+riversideDescription012(q)+'</div>';}
function canPlaceRiverside012(q,x,y){if(window.__noRiverside012)return '英式河畔市場暫停新增';if(!toolUnlocked458(toolMeta434(q.id)))return '城市 Lv.'+q.rank+' 解鎖';const err=canPlaceMulti(x,y,q.sz,'需 '+q.sz+'×'+q.sz+' 陸地');if(err)return err;const el=T(idx(x,y)).el||0;for(let dy=0;dy<q.sz;dy++)for(let dx=0;dx<q.sz;dx++){const t=T(idx(x+dx,y+dy));if(t.tree)return '先移除樹木';if(t.crater)return '隕石坑需先剷除';if(t.am502||t.parkMeter)return '先移除既有街道設施';if(t.fly475||t.ix475)return '既有高架交通擋住';if((t.el||0)!==el)return '需同一高度的平整地基';}return null;}
function installRiversideArt012(){
  if(!riversideArtCanonical012){const t0=performance.now(),a=window.BritishRiversideArchitecture012.buildAll(),bld={};if(Object.keys(a.buildings).length!==3||Object.keys(a.modules).length!==12)throw Error('GPT-012 requires 12 building and 12 path sprites');for(const q of Object.values(RIVERSIDE012)){const views=a.buildings[q.k];if(views?.length!==4)throw Error('GPT-012 requires four geometric views for '+q.k);for(let v=0;v<4;v++){const s=views[v];if(!s?.img||!s?.night||s.sz!==q.sz||s.view!==v)throw Error('Invalid GPT-012 sprite '+q.k+'/'+v);bld[q.k+'_1_'+v]={...s,smoke:[],__riverside012:1,__t479:1,__t547:{k:q.k,lv:1,v,bw:q.sz,bh:q.sz}};}}for(const q of Object.values(RIVERSIDE_PATH012))for(let v=0;v<4;v++){const s=a.modules[q.theme+'_'+v];if(!s?.img||!s?.night||s.sz!==1||s.view!==v||![s.w,s.h,s.ax,s.ay].every(Number.isFinite)||s.w<=0||s.h<=0)throw Error('Invalid GPT-012 path sprite '+q.theme+'/'+v);}riversideArtCanonical012={bld,modules:a.modules};window.__riversideArt012={builds:1,buildings:12,modules:12,total:24,ms:performance.now()-t0};}
  Object.assign(SPR.bld,riversideArtCanonical012.bld);SPR.riverside012=riversideArtCanonical012.modules;
}
function riversideObjects012(objs,sxOf,syOf,vis,lodFar){if(lodFar||window.__noRiversideArt012||!SPR.riverside012)return;for(const i of amCells502){const t=tiles[i],theme=riversideTheme012(t);if(!theme)continue;const x=i%N,y=(i/N)|0,sx=sxOf(x,y),sy=syOf(x,y);if(vis(sx,sy))objs.push({dep:viewDep(x,y)+.011,riversideModule012:theme,x,y,sx,sy});}}
function riversideModuleDraw012(g,o,z,depth,night,occ){const t=tiles[idx(o.x,o.y)],s=SPR.riverside012[o.riversideModule012+'_'+(((t.amx502?.turn012||0)+viewRotEff())&3)];if(!s)return;const x=o.sx+(32-s.ax)*z,y=o.sy+(32-s.ay)*z;g.drawImage(s.img,x,y,s.w*z,s.h*z);occ(s.img,x,y,s.w*z,s.h*z);if(depth>0&&s.night)night.push({img:s.night,x,y,w:s.w*z,h:s.h*z,grid487:1,gx:o.x,gy:o.y,warm649:1});}
// Observation-only ledger: copies the native commercial v2 after it has entered
// income/taxC. It never calculates a second tax, changes finances, or persists.
let riversideTaxLedger012={day:-1,total:0,rows:[]};
function resetRiversideTax012(){riversideTaxLedger012={day:-1,total:0,rows:[]};}
function beginRiversideTax012(){riversideTaxLedger012={day,total:0,rows:[]};}
function recordRiversideTax012(root,tax){const b=tiles[root]?.bld;if(!b||b.ref||!riversideKind012(b.k))return;const e=enterpriseRootInfo489(root);riversideTaxLedger012.total+=tax;riversideTaxLedger012.rows.push({root,k:b.k,tax,employed:e?.k===b.k?e.employed||0:0,utilization:e?.k===b.k?e.utilization||0:0});}
function riversideSpecs012(){return JSON.parse(JSON.stringify({buildings:Object.values(RIVERSIDE012),paths:Object.values(RIVERSIDE_PATH012).map(q=>({...q,base:'footpath502',cost:COST.footpath502}))}));}
// Evidence only reads native authorities. No ensure/dispatch/network rebuild,
// time advancement, worker allocation, source repair or financial assignment.
function riversideAt012(x,y){
  if(!inMap(x,y))return null;let root=idx(x,y),b=tiles[root]?.bld;if(b?.ref){root=idx(b.ref[0],b.ref[1]);b=tiles[root]?.bld;}const q=b&&!b.ref&&RIVERSIDE012[b.k];
  if(q){const e=enterpriseRootInfo489(root),on=riversideOperational012(root,b),same=e?.k===b.k,refs=[];for(let dy=0;dy<q.sz;dy++)for(let dx=0;dx<q.sz;dx++)if(dx||dy){const i=idx(root%N+dx,((root/N)|0)+dy);refs.push({i,bld:tiles[i]?.bld});}return JSON.parse(JSON.stringify({root,k:b.k,id:q.id,v:b.v,age:b.age,sz:b.sz,refCells:refs,built:riversideBuilt012(b),operational:on,power:!!b.pw,water:!!b.wa,powerState:POWER_ROOT_OK471[root]||0,powerAllocation:power471.loads?.find(r=>r.root===root)||null,waterState:{code:WATER_ROOT_STATE472[root]||0,state:WATER_STATE_TEXT472[WATER_ROOT_STATE472[root]||0]},waterDelivered:WATER_ROOT_DELIVERED472[root]||0,waterDemand:rootWaterDemandBase472(b)*waterProfile472(b)[1]*waterPolicyDemandMul472(b),road:sanRoadSeeds445(root).filter(i=>!roadIncidentClosed493(i)),enterprise:same?e:null,positions:on&&same?e.activePositions||0:0,employed:on&&same?e.employed||0:0,retailUnits:on&&same?Math.max(0,e.employed||0)/JOBSC[2]:0,activity:activityCapacity491(root,b),tax:riversideTaxLedger012.day===day?riversideTaxLedger012.rows.find(r=>r.root===root&&r.k===b.k)||null:null}));}
  const t=tiles[idx(x,y)],theme=riversideTheme012(t);return theme?{root:idx(x,y),theme,am502:t.am502,amx502:JSON.parse(JSON.stringify(t.amx502)),walkCost:(WALK_COST502[idx(x,y)]||0)*amWeatherFactor502('walk',1),baseWalkCost:.72,cost:COST.footpath502}:null;
}
function riversideEvidence012(){const roots=[],paths=[];for(const root of tickBld||[]){const b=tiles[root]?.bld;if(b&&!b.ref&&riversideKind012(b.k))roots.push(riversideAt012(root%N,(root/N)|0));}for(const i of amCells502)if(riversideTheme012(tiles[i]))paths.push(riversideAt012(i%N,(i/N)|0));return{day,roots,paths,retailUnits:riversideRetailUnits012(),taxLedger:JSON.parse(JSON.stringify({...riversideTaxLedger012,current:riversideTaxLedger012.day===day,authority:'native commercial tax v2, observed only'})),enterprise:enterpriseSnapshot489(),business:businessCycleSnapshot490(),mobility:mobilitySnapshot491(),art:{...window.__riversideArt012}};}
function riversideSelftest012(){const details=[],add=(name,ok,actual)=>details.push({name,ok:!!ok,actual});add('three bounded permanent IDs',Object.keys(RIVERSIDE012).join(',')==='278,279,280');for(const q of Object.values(RIVERSIDE012)){add(q.id+' paid fixed catalog and footprint',TOOLS.filter(t=>t.id===q.id).length===1&&COST[q.id]===q.cost&&MSZ[q.k]===q.sz&&toolSize458(q.id)===q.sz&&KNAME[q.k]===q.nm&&KCB[q.k]==='C');add(q.id+' native private retail only',MAYOR_ACTION_CATALOG470A[q.id]?.status==='manual-only'&&ENTERPRISE_CORE_K489.has(q.k)&&enterpriseGroupOf489({k:q.k,lv:1})==='commercial'&&enterprisePotentialJobs489(-1,{k:q.k,lv:1})===q.jobs&&publicJobCapacity491({k:q.k,age:9,lv:1})===0&&!LMCFG309[q.k]&&!UP_MAX[q.k]);add(q.id+' physical utility loads',powerLoadBase471({k:q.k,lv:1,sz:q.sz})===q.power&&rootWaterDemandBase472({k:q.k,lv:1,sz:q.sz})===q.water);for(let v=0;v<4;v++){const key=q.k+'_1_'+v,s=SPR.bld[key];add(key+' canonical authored view',s===riversideArtCanonical012?.bld[key]&&s?.__riverside012===1&&s.sz===q.sz&&s.view===v&&!!s.img&&!!s.night);}}for(const q of Object.values(RIVERSIDE_PATH012)){add(q.id+' ordinary T502 cost and metadata',TOOLS.filter(t=>t.id===q.id).length===1&&COST[q.id]===COST.footpath502&&AM_META502.footpath502.c===1);for(let v=0;v<4;v++)add(q.theme+'_'+v+' canonical path view',SPR.riverside012?.[q.theme+'_'+v]===riversideArtCanonical012?.modules[q.theme+'_'+v]&&!!SPR.riverside012?.[q.theme+'_'+v]?.img);}add('exact 24 assets built once',window.__riversideArt012?.total===24&&window.__riversideArt012.builds===1);add('prior bounded British registries retain their sizes',Object.keys(BRITISH004).length===3&&Object.keys(HIGHSTREET005).length===8&&Object.keys(RESIDENTIAL006).length===16&&Object.keys(PUBLICLIFE007).length===12&&Object.keys(STREETLIFE009).length===3&&Object.keys(MUSEUM010).length===1);return{ok:details.every(d=>d.ok),checks:details.map(d=>d.name+(d.ok?' ✓':' ✗')),details};}
/* GPT-012 LATE NATIVE HOOKS */
const __riversidePathCan012=canPlace;canPlace=function(id,x,y){const q=RIVERSIDE_PATH012[id];if(!q)return __riversidePathCan012(id,x,y);if(window.__noRiverside012)return '英式河畔市場暫停新增';if(!toolUnlocked458(toolMeta434(id)))return '城市 Lv.'+q.rank+' 解鎖';return __riversidePathCan012('footpath502',x,y);};
const __riversidePathCost012=placeCost;placeCost=function(id,x,y){return __riversidePathCost012(RIVERSIDE_PATH012[id]?'footpath502':id,x,y);};
const __riversidePathPlace012=doPlace;doPlace=function(id,x,y,silent){const q=RIVERSIDE_PATH012[id];if(!q)return __riversidePathPlace012(id,x,y,silent);const err=canPlace(id,x,y);if(err){if(!silent){toast(err,'bad');sErr();}return false;}if(!__riversidePathPlace012('footpath502',x,y,true))return false;tiles[idx(x,y)].amx502={british012:q.theme,turn012:riversideShoreTurn012(x,y)};activeMobilityMarkDirty502();if(!silent)toast(q.ic+' '+q.nm+' 完工','gold');return true;};
const __riversideVdraw012=vdraw574;vdraw574=function(o,b){return b&&riversideKind012(b.k)?((b.v+viewRotEff())&3):__riversideVdraw012(o,b);};
const __riversideLoad012=load;load=function(...a){resetRiversideTax012();return __riversideLoad012(...a);};
const __riversideNew012=newWorld;newWorld=function(...a){resetRiversideTax012();return __riversideNew012(...a);};
for(const q of Object.values(RIVERSIDE_PATH012)){COST[q.id]=COST.footpath502;TOOLS.push({id:q.id,cat:'road',ic:q.ic,nm:q.nm,pr:'$'+COST[q.id],unlockRank:q.rank});MAYOR_MANUAL_ONLY470A.add(q.id);}
CATALOG_SECTIONS458.find(q=>q[0]==='civic')[2].push(...Object.keys(RIVERSIDE_TOOL012));CATALOG_SECTIONS458.find(q=>q[0]==='transit')[2].push(...Object.keys(RIVERSIDE_PATH012));
const __riversideKeywords012=catalogKeywords458;catalogKeywords458=function(t){const q=RIVERSIDE_TOOL012[t?.id]||RIVERSIDE_PATH012[t?.id];return q?(__riversideKeywords012(t)+' '+q.en+' 英式 英國 河畔 河岸 拱廊 市場 花卉 蔬果 石岸 鐵欄 步道').toLowerCase():__riversideKeywords012(t);};
const __riversideInspect012=inspect;inspect=function(x,y){const out=__riversideInspect012(x,y),t=inMap(x,y)?tiles[idx(x,y)]:null,theme=riversideTheme012(t);if(theme&&$('#infoBody'))$('#infoBody').insertAdjacentHTML('beforeend','<div class="row">'+riversideDescription012(Object.values(RIVERSIDE_PATH012).find(q=>q.theme===theme))+'</div>');return out;};
