#!/usr/bin/env node
'use strict';
// JSON/source-only controls. Synthetic24 records are test data, never pixels.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{execFileSync}=require('node:child_process');
const fixed=require('./gardenlife-static-contract016'),native=require('./gardenlife-fingerprint016'),bridge=require('./gardenlife-historical-bridge016'),compat=require('./gardenlife-compatibility016');
function original18Controls016(input){const old=require('./streetscape-fingerprint015'),source=old.staticTest015.toString(),bindings={verifyFingerprint015:native.verifyFingerprint016,pinnedBaseline015:old.pinnedBaseline015,expectedAdditions:require('./streetscape-static-contract015').expectedAdditions,aggregate:native.aggregate,structuredClone};const file=fs.readFileSync(path.join(__dirname,'streetscape-fingerprint015.js'),'utf8');assert.equal(file,fixed.baseFile('streetscape-fingerprint015.js').toString());assert.equal(file.split(source).length,2);const fn=new vm.Script('(function('+Object.keys(bindings).join(',')+'){return ('+source+');})').runInThisContext()(...Object.values(bindings)),out=fn(input);assert.equal(out.rejected.length,18);return{...out,original18SourceSHA256:fixed.hash(source),original18StatementsExact:true};}
function original44ReleaseControls016(input){
 const projected=native.project016(input.fp,input.blocks),contract=require('./streetscape-release-contract015'),file='streetscape-release-contract015.test.js',source=fs.readFileSync(path.join(__dirname,file),'utf8');assert.equal(source,fixed.baseFile(file).toString());
 const start=' const block=Object.keys(native.blocks.entries)[0];',end='\n}\nconsole.log';assert.equal(source.split(start).length,2);assert.equal(source.split(end).length,2);const body=source.slice(source.indexOf(start),source.indexOf(end)),data={fp:projected.fp,blocks:input.blocks};contract.verifyApprovedNative015(data.fp,data.blocks);
 const run=new vm.Script('(function(native,contract,oldLeaf,newLeaf,rejected,assert,structuredClone,require){let nativeCases=0;'+body+';return{nativeCases,rejected};})').runInThisContext();
 const out=run(data,contract,Object.keys(require('./streetscape-fingerprint015').pinnedBaseline015().subs)[0],contract.expected[0],[],assert,structuredClone,require);assert.equal(out.nativeCases,44);assert.equal(out.rejected.length,44);
 return{ok:true,sourceOnly:true,gameExecuted:false,original44SourceSHA256:fixed.hash(body),original44StatementsExact:true,nativeNegativeCases:out.nativeCases,rejected:out.rejected,fullCurrentProof:projected.proof,completeProjectedLeaves:3091,completeBlocksCompared:1728,notCurrentReleaseApproval:true};
}
function test016(input,{synthetic=false}={}){
 const untouched=JSON.stringify(input),q=structuredClone(input),product=fixed.verifyStatic016();
 if(synthetic){assert.notEqual(process.env.GITHUB_ACTIONS,'true','Synthetic inputs cannot be current Actions native evidence');const old=require('./streetscape-release-contract015');old.verifyApprovedNative015(q.fp,q.blocks);assert.equal(q.version,'14.32');assert.equal(q.anchor,'T728');assert.equal(q.release,true);assert.equal(q.sourceSHA256,fixed.BASE_HTML_SHA256);for(const[n,key]of fixed.expectedAdditions.entries())q.fp.subs[key]={d:(n+1).toString(16).padStart(8,'0'),n:native.EMPTY_NIGHT_CRC,w:72,h:92,op:200};Object.assign(q.fp,native.aggregate(q.fp.subs));}
 else{const head=execFileSync('git',['rev-parse','HEAD'],{cwd:__dirname,encoding:'utf8'}).trim();assert.equal(q.checkedSHA,head);assert.equal(q.sourceSHA256,product.sourceSHA256);assert.equal(q.version,product.version);assert.equal(q.anchor,product.anchor);assert.equal(q.release,false);if(process.env.GITHUB_ACTIONS==='true')assert.equal(head,process.env.GITHUB_SHA);}
 const proof=native.verifyFingerprint016(q.fp,q.blocks),projected=native.project016(q.fp,q.blocks),theatre=bridge.theatreLineage014(q.fp,q.blocks),river=bridge.riversideLineage014(q.fp,q.blocks,product),museum=bridge.museumLineage014(q.fp,q.blocks,product);
 assert.deepEqual(projected.fp.subs,native.pinnedBaseline016().subs);assert.equal(projected.keys.length,24);
 for(const[v,count,removed]of[[theatre,2947,168],[river,2919,196],[museum,2895,220]]){assert.equal(v.ok,true);assert.equal(v.leaves,count);assert.equal(v.projectedKeys.length,removed);assert.equal(v.currentLeaves,3115);assert.equal(v.currentNativeFamilies,162);assert.equal(v.completeBlockRecordsExact,true);assert.equal(v.currentNativeProof.release,false);assert.equal(v.currentNativeProof.approvedNativeRecordsExact,false);}
 const original16=bridge.staticTest013(q),original10=bridge.nativeReleaseControls013(q),original18=original18Controls016(q),original44=original44ReleaseControls016(q),new20=native.staticTest016(q);
 assert.equal(original16.rejected.length,16);assert.equal(original16.originalNegativeControlStatementsExact,true);assert.equal(original10.nativeNegativeCases,10);assert.equal(original10.originalNativeControlStatementsExact,true);assert.equal(new20.rejected.length,20);
 const rejected=[];const reject=(name,mutate)=>{const z=structuredClone(q);mutate(z);const raw=JSON.stringify(z);for(const method of ['project014','theatreLineage014','riversideLineage014','museumLineage014'])assert.throws(()=>bridge[method](z.fp,z.blocks,product),undefined,name+'/'+method);assert.equal(JSON.stringify(z),raw);rejected.push(name);};
 for(const key of ['streetscape015.heritageLantern_0','bld.282_1_0','bld.281_1_0','bld.278_1_0','bld.277_1_0',Object.keys(native.pinnedBaseline016().subs)[0]])for(const field of['d','n','op','w','h'])reject(key+'/'+field,z=>{z.fp.subs[key][field]=typeof z.fp.subs[key][field]==='number'?z.fp.subs[key][field]+1:'f0f0f0f0';Object.assign(z.fp,native.aggregate(z.fp.subs));});
 reject('unknown addition cannot be projected',z=>{z.fp.subs['gardenLife016.unknown_0']={...z.fp.subs[fixed.expectedAdditions[0]]};Object.assign(z.fp,native.aggregate(z.fp.subs));});
 reject('complete block extra field',z=>z.blocks.entries[Object.keys(z.blocks.entries)[0]].extra=true);reject('complete block missing',z=>delete z.blocks.entries[Object.keys(z.blocks.entries)[0]]);
 const runs=compat.normalizationFixture016(),normal=compat.normalizeCompatibility016(runs,product);assert.equal(normal.metadataNormalization.normalizedFields,0);assert.equal(normal.metadataNormalization.applied,false);assert.deepEqual(normal.reference,normal.comparison);
 for(const[name,mutate]of[['old label',z=>z[0].result.find(w=>w.seed===900721).checkpoints[0].enterprise.version='14.31'],['missing world',z=>z[1].result.pop()],['missing checkpoint',z=>z[1].result[0].checkpoints.pop()]]){const z=structuredClone(runs);mutate(z);assert.throws(()=>compat.normalizeCompatibility016(z,product));rejected.push('world/'+name);}
 const fullLog=fs.readFileSync(path.join(__dirname,'AUTORUN-LOG.md'),'utf8'),log=bridge.historicalLog014(fullLog);assert.equal(log,execFileSync('git',['show',require('./streetlife-static-contract009').BASE+':AUTORUN-LOG.md'],{cwd:__dirname,encoding:'utf8',maxBuffer:8*1024*1024}));assert.throws(()=>bridge.historicalLog014(fullLog+'\n'));rejected.push('unbounded historical log edit');
 assert.equal(JSON.stringify(input),untouched);
 return{ok:true,sourceOnly:true,gameExecuted:false,syntheticNewRecords:synthetic,currentNativeRunClaimed:false,candidatePixelsGenerated:false,inputCheckedSHA:input.checkedSHA,proof,original16,original10,original18,original44,new20,rejected,normalizer:normal.metadataNormalization,fullHistoricalLogRecovered:true};
}
module.exports={test016,original18Controls016,original44ReleaseControls016};
if(require.main===module){const synthetic=process.argv[2]==='--synthetic',file=process.argv[synthetic?3:2];if(!file)throw Error('Use [--synthetic] native-fingerprint.json');console.log(JSON.stringify(test016(JSON.parse(fs.readFileSync(file)),{synthetic}),null,2));}
