#!/usr/bin/env node
'use strict';
// Source/JSON only. No game, browser, painter, canvas or proposal execution.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),crypto=require('node:crypto'),D=require('./mapedge-sampling-diagnostic018');
const hash=x=>crypto.createHash('sha256').update(x).digest('hex'),source=fs.readFileSync(path.join(__dirname,'waterfront-integration-qa018.js'),'utf8'),product=fs.readFileSync(path.join(__dirname,'index.html')),originalProductHash=hash(product),a=D.adaptDriver018(source),rejected=[];
assert.equal(hash(source),D.DRIVER_SHA256);assert.equal(a.proof.replacements,2);assert(a.proof.reversible&&a.proof.originalColdFlowByteExact&&!a.proof.productSourceSubstituted&&!a.proof.acceptanceGranted);new vm.Script(a.source);
const cold="  if(MODE==='coldload'){";assert.equal(a.source.slice(a.source.indexOf(cold),a.source.indexOf('  if(EDGE_MODE){')),source.slice(source.indexOf(cold),source.indexOf('  if(EDGE_MODE){')));
for(const token of["const edge=require('./mapedge-native-qa018')",'  if(EDGE_MODE){','  report.finalWorker=',"await cdp.send('Page.reload'",'for(let day=1;day<=3','for(let iteration=1;iteration<=2']){assert(source.includes(token));assert.throws(()=>D.adaptDriver018(source.replace(token,token+' /* changed */')));rejected.push('source pin rejects '+token);}
const fn=D.functions018.find(f=>f.name==='samplingDiagnosticPair018').toString();new vm.Script('('+fn+')');
for(const token of["this===context&&x===0&&y===0&&width===w&&height===h","active.underlayBeforeGround=true","active.suppressed++","draw.call(g,mask===3?cliff:copies[mask],sx,sy,64*z,56*z)",'g.putImageData(new ImageData(bytes,64,56),0,0)','window.MapEdgeRepair018=originalAPI','CanvasRenderingContext2D.prototype.clearRect=clear','Math.random=random',"if(frames.length<2)","kind:'ground-cache'",'outsideSamples.length<100'])assert(fn.includes(token),token);
assert(!/GV\.(?:load|save|newWorld|step|rebuild|place)|\.age\s*=|\.el\s*=|\.pw\s*=|\.wa\s*=|localStorage\.setItem|SPR\.cliff\s*=/.test(fn));
const good={proposalOnly:true,proposal:'underlay',worldExact:true,storageExact:true,canonicalCliffExact:true,canonical:true,apiRestored:true,randomCalls:0,copyProof:[{retainedMismatch:0,discardedOpaque:0}],frames:[true,false,true,false].map(legacy=>({legacy,callsExact:true,terrainExact:true,cacheClears:legacy?0:1,proposalDraws:12,calls:12,suppressed:12,underlayBeforeGround:true})),ground:{outside:0},full:{outside:0},restoredLegacy:{changed:0},repeatedProposal:{changed:0},preservedOutward:100,changedOutward:0};assert(D.diagnosticPass018(good));assert(D.diagnosticPass018({...good,proposal:'full-size-masked-copy'}));
for(const key of['worldExact','storageExact','canonicalCliffExact','canonical','apiRestored']){const q=structuredClone(good);q[key]=false;assert(!D.diagnosticPass018(q));rejected.push(key);}
for(const [name,edit]of[['outside ground',q=>q.ground.outside=1],['outside full',q=>q.full.outside=1],['outward loss',q=>q.changedOutward=1],['no retained soil',q=>q.preservedOutward=0],['legacy mismatch',q=>q.restoredLegacy.changed=1],['proposal mismatch',q=>q.repeatedProposal.changed=1],['source copy changed',q=>q.copyProof[0].retainedMismatch=1],['discarded half visible',q=>q.copyProof[0].discardedOpaque=1],['late underlay',q=>q.frames[1].underlayBeforeGround=false],['missing suppression',q=>q.frames[1].suppressed=0],['no actual cache clear',q=>q.frames[1].cacheClears=0],['wrong calls',q=>q.frames[2].callsExact=false],['terrain mutation',q=>q.frames[1].terrainExact=false],['RNG',q=>q.randomCalls=1]]){const q=structuredClone(good);edit(q);assert(!D.diagnosticPass018(q));rejected.push(name);}
assert(D.DIAGNOSTIC_BLOCK.includes("for(const rotation of[selectedRotation])"));assert(D.DIAGNOSTIC_BLOCK.includes('for(const zoom of[.75,1,1.6,2])'));assert(D.DIAGNOSTIC_BLOCK.includes("for(const proposal of['underlay','full-size-masked-copy'])"));assert(D.DIAGNOSTIC_BLOCK.includes('proposedPixelGatesPass'));assert(!D.DIAGNOSTIC_BLOCK.includes('check(\'proposal pixel'));assert(D.DIAGNOSTIC_BLOCK.includes("focusLabel:'image10'"));assert(D.DIAGNOSTIC_BLOCK.includes('report.diagnostic.errors.push'));
const workflow=fs.readFileSync(path.join(__dirname,'.github/workflows/waterfront-sampling-diagnostic018.yml'),'utf8');assert(workflow.includes('gpt/waterfront-edge-diagnostic-018'));assert(workflow.includes('contents: read'));assert(workflow.includes('cancel-in-progress: false'));assert(workflow.includes('WF018_MODE=mapedge${{ matrix.rotation }} node mapedge-sampling-diagnostic018.js'));assert(!workflow.includes('matrix.mode'));assert(workflow.includes('fail-fast: false'));assert(workflow.includes('rotation:'));assert(D.DIAGNOSTIC_BLOCK.includes('selectedRotation===1'));assert(D.DIAGNOSTIC_BLOCK.includes('selectedRotation=+REQUESTED_MODE.slice(-1)'));assert(!/git push|gh pr|gh workflow|continue-on-error: true/.test(workflow));assert.equal((workflow.match(/if: always\(\) && hashFiles/g)||[]).length,16);assert.equal(hash(fs.readFileSync(path.join(__dirname,'index.html'))),originalProductHash);
console.log(JSON.stringify({ok:true,sourceOnly:true,gameExecuted:false,pixelsExecuted:false,productChanged:false,full148Changed:false,adapter:a.proof,proposals:['underlay','full-size-masked-copy'],originalColdFlowByteExact:true,zeroOutsideAndExactOutwardRequired:true,pixelMismatchesDoNotStopMeasurement:true,rejected},null,2));
