#!/usr/bin/env node
'use strict';
// Source/JSON tests. Synthetic24 additions are visibly test data, never pixels.
const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path'),{execFileSync}=require('node:child_process');
const fixed=require('./quayside-static-contract017'),native=require('./quayside-fingerprint017'),bridge=require('./quayside-historical-bridge017'),compat=require('./quayside-compatibility017');
function projectApproved015(fp,blocks){const q=native.project017(fp,blocks),keys=require('./gardenlife-static-contract016').expectedAdditions,subs={};for(const[k,v]of Object.entries(q.fp.subs))if(!keys.includes(k))subs[k]=v;const old=require('./gardenlife-fingerprint016').pinnedBaseline016();assert.deepEqual(subs,old.subs);const projected={ok:true,subs,...native.aggregate(subs)};require('./streetscape-release-contract015').verifyApprovedNative015(projected,blocks);return{...q,fp:projected,keys:[...q.keys,...keys]};}
function original20Controls017(input){
 const old=require('./gardenlife-fingerprint016'),source=old.staticTest016.toString(),file=fs.readFileSync(path.join(__dirname,'gardenlife-fingerprint016.js'),'utf8');assert.equal(file,fixed.baseFile('gardenlife-fingerprint016.js').toString());assert.equal(file.split(source).length,2);
 const bindings={structuredClone,pinnedBaseline016:old.pinnedBaseline016,expectedAdditions:require('./gardenlife-static-contract016').expectedAdditions,aggregate:native.aggregate,verifyFingerprint016:native.verifyFingerprint017};const fn=new vm.Script('(function('+Object.keys(bindings).join(',')+'){return ('+source+');})').runInThisContext()(...Object.values(bindings)),out=fn(input);assert.equal(out.rejected.length,20);return{...out,original20SourceSHA256:fixed.hash(source),original20StatementsExact:true};
}
function originalLegacyControls017(name,input){
 const old=require('./gardenlife-legacy016.test'),file=fs.readFileSync(path.join(__dirname,'gardenlife-legacy016.test.js'),'utf8'),source=old[name].toString();assert.equal(file,fixed.baseFile('gardenlife-legacy016.test.js').toString());assert.equal(file.split(source).length,2);
 const bindings={fs,vm,assert,path,require,__dirname,structuredClone,fixed,native:{verifyFingerprint016:native.verifyFingerprint017,aggregate:native.aggregate,project016:projectApproved015}};
 return new vm.Script('(function('+Object.keys(bindings).join(',')+'){return ('+source+');})').runInThisContext()(...Object.values(bindings))(input);
}
function original36ReleaseControls017(input){
 const projected=native.project017(input.fp,input.blocks),contract=require('./gardenlife-release-contract016'),file='gardenlife-release-contract016.test.js',source=fs.readFileSync(path.join(__dirname,file),'utf8');assert.equal(source,fixed.baseFile(file).toString());
 const start=' const block=Object.keys(native.blocks.entries)[0];',end='\n}\nconsole.log';assert.equal(source.split(start).length,2);assert.equal(source.split(end).length,2);const body=source.slice(source.indexOf(start),source.indexOf(end)),data={fp:projected.fp,blocks:input.blocks};contract.verifyApprovedNative016(data.fp,data.blocks);
 const run=new vm.Script('(function(native,contract,oldLeaf,newLeaf,rejected,assert,structuredClone,require){let nativeCases=0;'+body+';return{nativeCases,rejected};})').runInThisContext();
 const out=run(data,contract,Object.keys(require('./gardenlife-fingerprint016').pinnedBaseline016().subs)[0],contract.expected[0],[],assert,structuredClone,require);assert.equal(out.nativeCases,36);assert.equal(out.rejected.length,36);
 return{ok:true,sourceOnly:true,gameExecuted:false,original36SourceSHA256:fixed.hash(body),original36StatementsExact:true,nativeNegativeCases:out.nativeCases,rejected:out.rejected,fullCurrentProof:projected.proof,completeProjectedLeaves:3115,completeBlocksCompared:1728,notCurrentReleaseApproval:true};
}
function test017(input,{synthetic=false}={}){
 const untouched=JSON.stringify(input),q=structuredClone(input),product=fixed.verifyStatic017();assert.equal(product.release,false);assert.equal(product.publicationApproved,false);assert.equal(product.version,'14.33');assert.equal(product.anchor,'T729');
 if(synthetic){assert.notEqual(process.env.GITHUB_ACTIONS,'true','Synthetic records cannot impersonate current Actions native evidence');require('./gardenlife-release-contract016').verifyApprovedNative016(q.fp,q.blocks);assert.equal(q.version,'14.33');assert.equal(q.anchor,'T729');assert.equal(q.release,true);assert.equal(q.sourceSHA256,fixed.BASE_HTML_SHA256);let n=0;for(const theme of fixed.THEMES)for(const view of[0,1,2,3])q.fp.subs['quayside017.'+theme+'_'+view]={d:(++n).toString(16).padStart(8,'0'),n:native.EMPTY_NIGHT_CRC,w:72,h:92,op:200};Object.assign(q.fp,native.aggregate(q.fp.subs));}
 else{const head=execFileSync('git',['rev-parse','HEAD'],{cwd:__dirname,encoding:'utf8'}).trim();assert.equal(q.checkedSHA,head);assert.equal(q.sourceSHA256,product.sourceSHA256);assert.equal(q.version,product.version);assert.equal(q.anchor,product.anchor);assert.equal(q.release,false);if(process.env.GITHUB_ACTIONS==='true')assert.equal(head,process.env.GITHUB_SHA);}
 const proof=native.verifyFingerprint017(q.fp,q.blocks),projected=native.project017(q.fp,q.blocks),theatre=bridge.theatreLineage014(q.fp,q.blocks),river=bridge.riversideLineage014(q.fp,q.blocks,product),museum=bridge.museumLineage014(q.fp,q.blocks,product);
 assert.deepEqual(projected.fp.subs,native.pinnedBaseline017().subs);assert.equal(projected.keys.length,24);
 for(const[v,count,removed]of[[theatre,2947,192],[river,2919,220],[museum,2895,244]]){assert.equal(v.ok,true);assert.equal(v.leaves,count);assert.equal(v.projectedKeys.length,removed);assert.equal(v.currentLeaves,3139);assert.equal(v.currentNativeFamilies,163);assert.equal(v.completeBlockRecordsExact,true);assert.equal(v.currentNativeProof.release,false);assert.equal(v.currentNativeProof.approvedNativeRecordsExact,false);assert.equal(v.currentNativeProof.publicationApproved,false);}
 const original16=bridge.staticTest013(q),original10=bridge.nativeReleaseControls013(q),original18=originalLegacyControls017('original18Controls016',q),original44=originalLegacyControls017('original44ReleaseControls016',q),original20=original20Controls017(q),original36=original36ReleaseControls017(q),new29=native.staticTest017(q);
 assert.equal(original16.rejected.length,16);assert.equal(original16.originalNegativeControlStatementsExact,true);assert.equal(original10.nativeNegativeCases,10);assert.equal(original10.originalNativeControlStatementsExact,true);assert.equal(original18.rejected.length,18);assert.equal(original44.nativeNegativeCases,44);assert.equal(original20.rejected.length,20);assert.equal(original36.nativeNegativeCases,36);assert.equal(new29.rejected.length,29);
 const rejected=[];const reject=(name,mutate)=>{const z=structuredClone(q);mutate(z);const raw=JSON.stringify(z);for(const method of ['project014','theatreLineage014','riversideLineage014','museumLineage014'])assert.throws(()=>bridge[method](z.fp,z.blocks,product),undefined,name+'/'+method);assert.equal(JSON.stringify(z),raw);rejected.push(name);};
 for(const key of ['gardenLife016.pumpCourt_0','streetscape015.heritageLantern_0','bld.282_1_0','bld.281_1_0','bld.278_1_0','bld.277_1_0',Object.keys(native.pinnedBaseline017().subs)[0]])for(const field of['d','n','op','w','h'])reject(key+'/'+field,z=>{z.fp.subs[key][field]=typeof z.fp.subs[key][field]==='number'?z.fp.subs[key][field]+1:'f0f0f0f0';Object.assign(z.fp,native.aggregate(z.fp.subs));});
 for(const key of require('./gardenlife-static-contract016').expectedAdditions)reject('approved016 whole record/'+key,z=>{z.fp.subs[key].d=z.fp.subs[key].d==='00000000'?'ffffffff':'00000000';Object.assign(z.fp,native.aggregate(z.fp.subs));});
 reject('unknown addition cannot be projected',z=>{z.fp.subs['quayside017.unknown_0']={...z.fp.subs[fixed.expectedAdditions[0]]};Object.assign(z.fp,native.aggregate(z.fp.subs));});
 reject('complete block extra field',z=>z.blocks.entries[Object.keys(z.blocks.entries)[0]].extra=true);reject('complete block missing',z=>delete z.blocks.entries[Object.keys(z.blocks.entries)[0]]);
 const runs=compat.normalizationFixture017(),normal=compat.normalizeCompatibility017(runs,product);assert.equal(normal.metadataNormalization.normalizedFields,0);assert.equal(normal.metadataNormalization.applied,false);assert.deepEqual(normal.reference,normal.comparison);
 for(const[name,mutate]of[['old label',z=>z[0].result.find(w=>w.seed===900721).checkpoints[0].enterprise.version='14.32'],['missing world',z=>z[1].result.pop()],['missing checkpoint',z=>z[1].result[0].checkpoints.pop()]]){const z=structuredClone(runs);mutate(z);assert.throws(()=>compat.normalizeCompatibility017(z,product));rejected.push('world/'+name);}
 const fullLog=fs.readFileSync(path.join(__dirname,'AUTORUN-LOG.md'),'utf8'),log=bridge.historicalLog014(fullLog);assert.equal(log,execFileSync('git',['show',require('./streetlife-static-contract009').BASE+':AUTORUN-LOG.md'],{cwd:__dirname,encoding:'utf8',maxBuffer:8*1024*1024}));assert.throws(()=>bridge.historicalLog014(fullLog+'\n'));rejected.push('unbounded historical log edit');
 assert.equal(JSON.stringify(input),untouched);
 return{ok:true,sourceOnly:true,gameExecuted:false,syntheticNewRecords:synthetic,currentNativeRunClaimed:false,candidatePixelsGenerated:false,inputCheckedSHA:input.checkedSHA,proof,original16,original10,original18,original44,original20,original36,new29,rejected,normalizer:normal.metadataNormalization,fullHistoricalLogRecovered:true};
}
module.exports={test017,original20Controls017,originalLegacyControls017,original36ReleaseControls017,projectApproved015};
if(require.main===module){const synthetic=process.argv[2]==='--synthetic',file=process.argv[synthetic?3:2];if(!file)throw Error('Use [--synthetic] native-fingerprint.json');console.log(JSON.stringify(test017(JSON.parse(fs.readFileSync(file)),{synthetic}),null,2));}
