'use strict';
// Source, mocked observations and optional archived/current JSON only. No
// native game, canvas, painter or new browser RGBA proof is executed here.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),fixed=require('./waterfront-quarter-contract019'),S=require('./waterfront-quarter-session019'),old=require('./waterfront-session-fingerprint018'),{aggregate}=require('./streetlife-fingerprint-qa009');
function sourceControls019(){
 const sources=S.readWorkerSources019(),adapted=sources.observer;assert(adapted.proof.reverseExact);assert(adapted.proof.onlyFixtureBindingChanged);assert.equal(adapted.proof.edits.length,1);assert.equal(adapted.proof.edits[0].count,1);
 assert.equal(adapted.source.replace(adapted.proof.edits[0].to,adapted.proof.edits[0].from),old.observeWorkerSession018.toString());
 for(const source of[old.observeWorkerSession018.toString().replace('const Q=','const Q2='),old.observeWorkerSession018.toString()+'\n',old.observeWorkerSession018.toString().replace('fullAtlasExact:','fullAtlasExact:true,oldExact:')])assert.throws(()=>S.adaptWorkerObserver019(source));
 const purity={worldExact:true,storageExact:true,fullAtlasExact:true,workerObjectExact:true,workerCanvasExact:true,mathRandomRestored:true},atlas={worker12:{img:{mock:true}}},fp={mock:true},GV={art574:{SPR:()=>atlas},fp536:()=>fp},window={__quarterQA019:{world:()=>'{"mock":"world"}',storage:()=>({mock:'storage'})}};
 const result=new vm.Script('('+adapted.source+')(legacyWorkerProof,"mock source")').runInNewContext({window,GV,legacyWorkerProof:()=>({mock:true}),Math,JSON});assert.deepEqual(JSON.parse(JSON.stringify(result)),{legacy:{mock:true},purity});
 const before={ok:true,subs:{old:{d:'12345678',w:2,h:2,op:2,n:null}},families:{old:{crc:'12345678'}},stats:{leaves:1}},after=structuredClone(before);after.subs.worker12={...old.WORKER_LEAF};after.subs.old.op=1;after.families.worker12={crc:'23456789'};after.stats.leaves++;
 const blocks={ok:true,count:1,fam:'12345678',entries:{block:{d:'12345678',n:null}}},end=structuredClone(blocks);end.entries.block.d='87654321';end.fam='87654321';const raw=JSON.stringify([before,after,blocks,end]),delta=S.sessionDelta019(before,after,blocks,end);
 assert.equal(delta.atlasExact,false);assert.equal(delta.blocksExact,false);assert.deepEqual(delta.leaf.counts,{added:1,removed:0,changed:1});assert.equal(delta.leaf.added[0].key,'worker12');assert.deepEqual(delta.leaf.changed[0],{key:'old',before:before.subs.old,after:after.subs.old});assert.equal(delta.block.changed[0].key,'block');assert.equal(delta.blockMetadata.changed[0].key,'fam');assert.equal(JSON.stringify([before,after,blocks,end]),raw);
 const many=Object.fromEntries(Array.from({length:100},(_,i)=>['leaf'+i,{d:'12345678'}])),bounded=S.recordDelta019({},many);assert.equal(bounded.counts.added,100);assert.equal(bounded.added.length,24);assert.equal(bounded.truncated,true);assert.equal(S.recordDelta019(many,{}).counts.removed,100);for(const limit of[0,65,1.5,Infinity])assert.throws(()=>S.recordDelta019({},many,limit));
 const runner=fs.readFileSync('probe-waterfront-quarter019.js','utf8'),snap=runner.indexOf('report.finalFingerprint=final;'),validate=runner.indexOf('session.verifySessionFingerprint019(');assert(snap>0&&validate>snap);assert(runner.slice(snap,validate).includes('save();'));assert(runner.includes('workerSources.proofSource'));assert(runner.includes('workerSources.observer.source'));assert(runner.indexOf('delete report.finalFingerprint;')>validate);assert(runner.includes('report.finalDelta=session.sessionDelta019(fp,final,blocks,finalBlocks)'));
 return{ok:true,sourceOnly:true,mockedObserverOnly:true,gameOrPainterExecuted:false,newBrowserRGBAProofExecuted:false,original018SourceExact:true,oneReversibleFixtureBinding:true,boundedDiagnosticRows:24};
}
function nativeDataControls019(input){
 const inputRaw=JSON.stringify(input),sources=S.readWorkerSources019(),purity={worldExact:true,storageExact:true,fullAtlasExact:true,workerObjectExact:true,workerCanvasExact:true,mathRandomRestored:true};
 const proof={legacy:{present:true,width:56,height:9,CW:7,CH:9,ax:3,ay:8,exact:true,deterministic:true,mathRandomCalls:0,reference:old.PROOF_REFERENCE},purity},absent={legacy:{present:false,exact:false,deterministic:false,mathRandomCalls:0},purity};
 const after=structuredClone(input.fp);after.subs.worker12={...old.WORKER_LEAF};Object.assign(after,aggregate(after.subs));
 const base={before:structuredClone(input.fp),after,beforeBlocks:structuredClone(input.blocks),afterBlocks:structuredClone(input.blocks),proof,provenance:sources.provenance,preflight:input},run=q=>S.verifySessionFingerprint019(q.before,q.after,q.beforeBlocks,q.afterBlocks,q.proof,q.provenance,q.preflight),rejected=[];
 const present=run(base),empty=run({...base,after:input.fp,proof:absent});assert(present.legacy.nativeRGBAProofVerified);assert(empty.legacy.absentWorkerProofVerified);assert.equal(present.fullBootLeaves,3179);assert.equal(present.finalLeaves,3180);assert.equal(present.finalFamilies,166);
 function reject(name,edit,source=base){const q=structuredClone(source);edit(q);const raw=JSON.stringify(q);assert.throws(()=>run(q),undefined,name);assert.equal(JSON.stringify(q),raw,'Rejected input mutated: '+name);rejected.push(name);}
 const oldLeaf=Object.keys(input.fp.subs).find(k=>!k.startsWith('waterfrontQuarter019.')),newLeaf=fixed.expectedAdditions.find(k=>k.includes('harbourLantern')),family=Object.keys(input.fp.families)[0],block=Object.keys(input.blocks.entries)[0],changedCRC=v=>v==='87654321'?'12345678':'87654321';
 for(const key of[oldLeaf,newLeaf]){
  for(const field of['d','n','w','h','op'])reject('full existing leaf '+key+'/'+field,q=>{const leaf=q.after.subs[key];leaf[field]=field==='d'||field==='n'?changedCRC(leaf[field]):leaf[field]+1;Object.assign(q.after,aggregate(q.after.subs));});
  reject('missing leaf '+key,q=>{delete q.after.subs[key];Object.assign(q.after,aggregate(q.after.subs));});reject('extra leaf field '+key,q=>q.after.subs[key].extra=true);
 }
 reject('changed remaining new leaf',q=>{q.after.subs[fixed.expectedAdditions[0]].d=changedCRC(q.after.subs[fixed.expectedAdditions[0]].d);Object.assign(q.after,aggregate(q.after.subs));});
 reject('unknown added leaf',q=>{q.after.subs.unknown={...old.WORKER_LEAF};Object.assign(q.after,aggregate(q.after.subs));});reject('unknown worker instead',q=>{q.after.subs.worker13=q.after.subs.worker12;delete q.after.subs.worker12;Object.assign(q.after,aggregate(q.after.subs));});
 for(const field of['d','n','w','h','op'])reject('worker record '+field,q=>{const leaf=q.after.subs.worker12;leaf[field]=field==='d'||field==='n'?changedCRC(leaf[field]):leaf[field]+1;Object.assign(q.after,aggregate(q.after.subs));});reject('worker extra field',q=>q.after.subs.worker12.extra=true);
 reject('existing family changed',q=>q.after.families[family].crc='00000000');reject('quarter family changed',q=>q.after.families.waterfrontQuarter019.crc='00000000');reject('worker family changed',q=>q.after.families.worker12.crc='00000000');reject('false stats',q=>q.after.stats.leaves++);reject('extra top-level',q=>q.after.extra=true);reject('failed fingerprint',q=>q.after.ok=false);
 reject('missing worker proof',q=>delete q.proof);reject('malformed worker proof',q=>q.proof=null);reject('unknown worker proof field',q=>q.proof.extra=true);reject('missing full RGBA',q=>delete q.proof.legacy.exact);
 for(const[field,value]of[['present',false],['width',55],['height',10],['CW',8],['CH',10],['ax',4],['ay',9],['exact',false],['deterministic',false],['mathRandomCalls',1],['reference','unverified']])reject('worker proof '+field,q=>q.proof.legacy[field]=value);
 for(const field of Object.keys(purity))reject('observer purity '+field,q=>q.proof.purity[field]=false);
 for(const field of Object.keys(sources.provenance))reject('source provenance '+field,q=>q.provenance[field]='changed');
 reject('changed complete block',q=>q.afterBlocks.entries[block].d=changedCRC(q.afterBlocks.entries[block].d));reject('missing block',q=>delete q.afterBlocks.entries[block]);reject('extra block field',q=>q.afterBlocks.entries[block].extra=true);reject('false block aggregate',q=>q.afterBlocks.fam='00000000');reject('false block count',q=>q.afterBlocks.count--);reject('failed block enumeration',q=>q.afterBlocks.ok=false);reject('block top-level field',q=>q.afterBlocks.extra=true);
 reject('boot mismatch to preflight',q=>{q.before.subs[newLeaf].d=changedCRC(q.before.subs[newLeaf].d);Object.assign(q.before,aggregate(q.before.subs));});reject('boot worker already present',q=>q.before=structuredClone(q.after));reject('unverified preflight',q=>q.preflight=null);reject('wrong preflight blocks',q=>q.beforeBlocks={ok:true,count:1728,fam:'00000000',entries:{}});
 reject('absent worker conceals mutation',q=>{q.after.subs[newLeaf].d=changedCRC(q.after.subs[newLeaf].d);Object.assign(q.after,aggregate(q.after.subs));},{...base,after:structuredClone(input.fp),proof:absent});reject('absent worker claims present proof',q=>q.proof=proof,{...base,after:structuredClone(input.fp),proof:absent});
 assert.equal(JSON.stringify(input),inputRaw);return{ok:true,dataOnly:true,newBrowserRGBAProofExecuted:false,nativeRuntimeAcceptance:false,syntheticWorkerAndProof:true,inputCheckedSHA:input.checkedSHA,inputSourceSHA256:input.sourceSHA256,inputJSONSHA256:fixed.hash(inputRaw),fullBootLeaves:3179,syntheticFinalLeaves:3180,completeInputBlocks:1728,rejected};
}
const sourceResult019=sourceControls019();
module.exports={sourceControls019,nativeDataControls019,sourceResult019};
if(require.main===module){const out={source:sourceResult019};if(process.argv[2]){const bytes=fs.readFileSync(process.argv[2]);out.inputFileSHA256=fixed.hash(bytes);out.data=nativeDataControls019(JSON.parse(bytes));}console.log(JSON.stringify(out,null,2));}
