#!/usr/bin/env node
'use strict';
// Pure source/JSON controls. Neither synthetic proofs nor archived data claim
// a new browser/painter/full-RGBA run. That proof is mandatory in Actions.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{isDeepStrictEqual:eq}=require('node:util'),fixed=require('./waterfront-static-contract018'),{aggregate}=require('./streetlife-fingerprint-qa009'),S=require('./waterfront-session-fingerprint018');
const sources=S.readWorkerSources018();new vm.Script('('+S.observeWorkerSession018.toString()+')');
const subs={};for(let n=0;n<3147;n++)subs['synthetic'+(n%164)+'.leaf'+n]={d:'12345678',n:null,w:2,h:2,op:2};
const before={ok:true,subs,...aggregate(subs)},after=structuredClone(before);after.subs.worker12={...S.WORKER_LEAF};Object.assign(after,aggregate(after.subs));
const blocks={ok:true,count:1728,fam:'12345678',entries:Object.fromEntries(Array.from({length:1728},(_,n)=>['synthetic-block'+n,{d:'12345678',n:'23456789'}]))};
const purity={worldExact:true,storageExact:true,fullAtlasExact:true,workerObjectExact:true,workerCanvasExact:true,mathRandomRestored:true},proof={legacy:{present:true,width:56,height:9,CW:7,CH:9,ax:3,ay:8,exact:true,deterministic:true,mathRandomCalls:0,reference:S.PROOF_REFERENCE},purity},absent={legacy:{present:false,exact:false,deterministic:false,mathRandomCalls:0},purity};
const input={before,after,beforeBlocks:blocks,afterBlocks:structuredClone(blocks),proof,provenance:sources.provenance},run=q=>S.verifySessionFingerprint018(q.before,q.after,q.beforeBlocks,q.afterBlocks,q.proof,q.provenance),rejected=[];
assert(run(input).workerPresent);assert(run({...input,after:before,proof:absent}).absentWorkerProofVerified);
function reject(name,edit,original=input){const q=structuredClone(original);edit(q);const raw=JSON.stringify(q);assert.throws(()=>run(q),undefined,name);assert.equal(JSON.stringify(q),raw,'Rejected data must not mutate: '+name);rejected.push(name);}
const oldKey=Object.keys(before.subs)[0],family=Object.keys(before.families)[0];
for(const[field,value]of[['d','87654321'],['n','87654321'],['w',3],['h',3],['op',1]])reject('changed full prior leaf '+field,q=>{q.after.subs[oldKey][field]=value;Object.assign(q.after,aggregate(q.after.subs));});
reject('missing prior leaf',q=>{delete q.after.subs[oldKey];Object.assign(q.after,aggregate(q.after.subs));});reject('extra prior record field',q=>q.after.subs[oldKey].extra=1);
for(const field of['crc','leaves','px','op','night'])reject('changed old family '+field,q=>q.after.families[family][field]='changed');
for(const field of['leaves','families','dayNonEmpty','nightNonEmpty'])reject('false aggregate '+field,q=>q.after.stats[field]++);
reject('extra family',q=>q.after.families.unknown={...q.after.families.worker12});reject('unknown added leaf',q=>{q.after.subs.unknown={...S.WORKER_LEAF};Object.assign(q.after,aggregate(q.after.subs));});reject('unknown addition replacing worker',q=>{delete q.after.subs.worker12;q.after.subs.worker13={...S.WORKER_LEAF};Object.assign(q.after,aggregate(q.after.subs));});
for(const[field,value]of[['d','87654321'],['n','87654321'],['w',57],['h',10],['op',131]])reject('worker full record '+field,q=>{q.after.subs.worker12[field]=value;Object.assign(q.after,aggregate(q.after.subs));});reject('extra worker field',q=>q.after.subs.worker12.nop=0);
reject('changed complete block',q=>q.afterBlocks.entries['synthetic-block0'].d='87654321');reject('missing block',q=>delete q.afterBlocks.entries['synthetic-block0']);reject('extra block field',q=>q.afterBlocks.entries['synthetic-block0'].extra=true);reject('changed block aggregate',q=>q.afterBlocks.fam='87654321');reject('changed block count',q=>q.afterBlocks.count--);reject('failed block enumeration',q=>q.afterBlocks.ok=false);
reject('malformed proof',q=>q.proof=null);reject('missing proof',q=>delete q.proof);reject('extra proof field',q=>q.proof.extra=true);
for(const[field,value]of[['present',false],['width',55],['height',8],['CW',8],['CH',10],['ax',4],['ay',9],['exact',false],['deterministic',false],['mathRandomCalls',1],['mathRandomCalls','0'],['reference','synthetic unsupported claim']])reject('invalid browser proof '+field+':'+value,q=>q.proof.legacy[field]=value);
reject('missing full RGBA comparison',q=>delete q.proof.legacy.exact);reject('extra legacy proof field',q=>q.proof.legacy.extra=true);
for(const field of Object.keys(purity))reject('observer impurity '+field,q=>q.proof.purity[field]=false);
for(const field of Object.keys(sources.provenance))reject('unpinned source '+field,q=>q.provenance[field]='changed');
reject('no source provenance',q=>delete q.provenance);reject('extra source claim',q=>q.provenance.extra=true);
const empty={...input,after:structuredClone(before),proof:absent};reject('absent worker hides old mutation',q=>{q.after.subs[oldKey].d='87654321';Object.assign(q.after,aggregate(q.after.subs));},empty);reject('absent worker hides unknown addition',q=>{q.after.subs.surprise={...S.WORKER_LEAF};Object.assign(q.after,aggregate(q.after.subs));},empty);reject('absent worker false present proof',q=>q.proof=proof,empty);reject('absent worker extra metadata',q=>q.proof.legacy.width=56,empty);reject('absent worker invented RGBA',q=>q.proof.legacy.exact=true,empty);reject('absent worker malformed null proof',q=>q.proof=null,empty);reject('present worker absent proof',q=>q.proof=absent);
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),legacy=fs.readFileSync(path.join(__dirname,'publiclife-integration-qa.js'),'utf8'),baseHTML=fixed.baseFile('index.html').toString(),baseLegacy=fixed.baseFile('publiclife-integration-qa.js').toString();
for(const[name,edit]of[['current worker source',q=>q[0]=q[0].replace('const CW=7,CH=9','const CW=8,CH=9')],['both worker sources',q=>{q[0]=q[0].replace('const CW=7,CH=9','const CW=8,CH=9');q[1]=q[1].replace('const CW=7,CH=9','const CW=8,CH=9');}],['current legacy proof',q=>q[2]=q[2].replace('exact:same(actual.img,expected.img)','exact:true')],['both legacy proofs',q=>{q[2]=q[2].replace('exact:same(actual.img,expected.img)','exact:true');q[3]=q[3].replace('exact:same(actual.img,expected.img)','exact:true');}],['modified old runtime file',q=>q[2]+='\n// altered']]){const q=[html,baseHTML,legacy,baseLegacy];edit(q);assert.throws(()=>S.verifyWorkerSources018(...q));rejected.push(name);}
const runner=fs.readFileSync(path.join(__dirname,'waterfront-integration-qa018.js'),'utf8');assert(runner.includes('session.verifySessionFingerprint018'));assert(runner.includes('workerSources.proofSource'));assert(runner.includes('report.finalAssets=recordAssets'));assert(runner.includes('eq(report.finalAssets,report.initialAssets)'));assert(runner.includes("call('waterfrontCanonical018')"));
const report={ok:true,sourceOnly:true,syntheticDataOnly:true,gameExecuted:false,artExecuted:false,newBrowserRGBAProofExecuted:false,workerSourceSHA256:S.WORKER_SOURCE_SHA256,legacyProofSHA256:S.LEGACY_PROOF_SHA256,originalLegacyFunctionByteExact:true,syntheticBaselineLeaves:3147,syntheticCurrentLeaves:3148,completeSyntheticBlocks:1728,rejected,archived:[]};
if(process.argv[2]==='--archived'){
 const files=process.argv.slice(3);assert(files.length>=2,'Provide one archived preflight and at least one archived manifest');const baseBytes=fs.readFileSync(files[0]),base=JSON.parse(baseBytes);
 for(const file of files.slice(1)){const bytes=fs.readFileSync(file),q=JSON.parse(bytes);assert.equal(q.sourceSHA256,base.sourceSHA256,'Archived source equivalence required; QA heads may differ and are disclosed');assert(q.finalFingerprint&&q.finalBlocks,'Full archived failing records required');const data=S.compareSessionData018(base.fp,q.finalFingerprint,base.blocks,q.finalBlocks);assert.equal(data.workerPresent,true);assert(fs.readFileSync(file).equals(bytes));report.archived.push({file,sha256:fixed.hash(bytes),archived:true,archivedCheckedSHA:q.checkedSHA,comparisonPreflightSHA:base.checkedSHA,identicalProductSourceSHA256:q.sourceSHA256,dataComparison:data,newBrowserRGBAProofExecuted:false,nativeRuntimeAcceptance:false,originalFailurePreserved:q.failures,disclosure:'Archived full-record comparison only. This does not supply or claim the new runtime full-RGBA proof.'});}
 assert(fs.readFileSync(files[0]).equals(baseBytes));report.archivedPreflightSHA256=fixed.hash(baseBytes);
}else assert.equal(process.argv.length,2,'Use optional --archived preflight.json manifest.json ...');
console.log(JSON.stringify(report,null,2));
