#!/usr/bin/env node
'use strict';
// Source and synthetic JSON only. No game, browser, native canvas or painter.
const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path'),{functions018}=require('./waterfront-gameplay018'),V=require('./waterfront-lifecycle-contract018');
for(const f of functions018)new vm.Script('('+f.toString()+')');
const rejected=[],negative=(name,original,validate,edit)=>{const q=structuredClone(original);edit(q);assert.equal(validate(q),false,name);rejected.push(name);};
const root=(n,age)=>{const x=63+n*3,y=64,r=y*72+x,v=n<2?2:0,theme=V.THEMES[n],b={k:287,lv:1,v,sz:2,age,...(theme?{waterfront018:theme}:{})};return{id:V.IDS[n],theme,x,y,root:r,appearance:theme?{theme,root:r,v}:null,native:{root:r,k:287,sz:2,v,age,built:age>=9,operational:age>=9,powerState:1,waterState:{code:4},waterDelivered:1.8,road:[r-72],positions:age>=9?5:0,employed:age>=9?5:0,activity:{work:age>=9?5:0,publicJobs:age>=9?5:0,leisure:age>=9?70:0,education:0,services:0},upkeep:age>=9?3:0,coverageStamp:null},cells:[{bld:b},...[1,2,3].map(()=>({bld:{k:287,ref:[x,y]}}))]};};
const days=Array.from({length:10},(_,age)=>({day:20+age,roots:[0,1,2].map(n=>root(n,age)),identity:{tags:[{root:4671,k:287,ref:null,appearance:'lifeboatHall'},{root:4674,k:287,ref:null,appearance:'canalTollhouse'}]}}));
assert(V.validConstruction018(days,20));assert(V.validRoots018(days[9],9,true));assert(V.sameNewIdentity018(days[0],days[9],9));
for(const[name,edit]of[['missing day',q=>q.pop()],['duplicate day',q=>q[4].day--],['skipped construction',q=>{q[4].roots[0].native.age=9;q[4].roots[0].cells[0].bld.age=9;}],['early public jobs',q=>q[3].roots[0].native.positions=5],['early leisure',q=>q[3].roots[0].native.activity.leisure=70],['early upkeep',q=>q[3].roots[0].native.upkeep=3],['early coverage',q=>q[3].roots[0].native.coverageStamp={field:'park'}],['missing completion',q=>q[9].roots[0].native.built=false],['lost appearance',q=>delete q[5].roots[0].cells[0].bld.waterfront018],['wrong appearance',q=>q[5].roots[0].appearance.theme='canalTollhouse'],['tagged original',q=>q[5].roots[2].cells[0].bld.waterfront018='lifeboatHall'],['tagged reference',q=>q[5].roots[0].cells[1].bld.waterfront018='lifeboatHall'],['wrong reference',q=>q[5].roots[0].cells[1].bld.ref=[1,1]],['lost native root',q=>q[5].roots.pop()],['bad direction',q=>q[5].roots[0].cells[0].bld.v=8],['duplicate root',q=>q[5].roots[1]=structuredClone(q[5].roots[0])]])negative(name,days,q=>V.validConstruction018(q,20),edit);
for(const[field,value]of[['powerState',0],['waterDelivered',0],['employed',0],['positions',0],['road',[]],['operational',false]])negative('readiness '+field,days[9],q=>V.validRoots018(q,9,true),q=>q.roots[0].native[field]=value);
for(const[field,value]of[['v',1],['k',286],['sz',1],['age',10]])negative('cold native '+field,days[9],q=>V.sameNewIdentity018(days[0],q,9),q=>q.roots[0].native[field]=value);
negative('cold saved appearance',days[9],q=>V.sameNewIdentity018(days[0],q,9),q=>q.identity.tags[0].appearance='canalTollhouse');
// fiscal515 records the selected public tool ID, never an inferred inner alias.
const html=fs.readFileSync(path.join(__dirname,'index.html'),'utf8'),fiscalNeedle='fiscal515.capitalLedger.push({d:day,tool:toolId,x,y,cost:Math.round(cost||Math.max(0,before-money)),k:tiles[idx(x,y)]?.bld?.k||0})';
assert.equal(html.split(fiscalNeedle).length,2);assert(html.indexOf(fiscalNeedle)>html.indexOf('/* GPT-018 LATE NATIVE HOOKS */'));
const payments=V.IDS.map((id,n)=>({id,quote:{tool:id,x:63+n*3,y:64,cost:1250},capital:[{d:20,tool:id,x:63+n*3,y:64,cost:1250,k:287}],ok:true,charged:1250,undo:true,undoExact:true,redo:true,redoExact:true})),placement={oldIdentitiesExact:true,payments,placementDay:20,initial:days[0]};assert(V.validPlacement018(placement));
for(let side=0;side<3;side++){
 const p=payments[side],valid=q=>V.validCapital018(q.id,q.quote,q.capital,20);assert(valid(p));
 for(const[name,edit]of [['wrong selected tool',q=>q.capital[0].tool=V.IDS[(side+1)%3]],['wrong native kind',q=>q.capital[0].k=288],['wrong transaction day',q=>q.capital[0].d++],['wrong x',q=>q.capital[0].x++],['wrong y',q=>q.capital[0].y++],['wrong rounded quote',q=>q.capital[0].cost++],['missing ledger row',q=>q.capital=[]],['double capital entry',q=>q.capital.push({...q.capital[0]})],['missing date',q=>delete q.capital[0].d],['unexpected ledger field',q=>q.capital[0].extra=true],['different quote identity',q=>q.quote.tool='unknown']])negative(p.id+' ledger '+name,p,valid,edit);
}
for(const side of[0,1])negative('inner native alias must not replace selected '+V.IDS[side],placement,V.validPlacement018,q=>q.payments[side].capital[0].tool='manorStableCourt014');
negative('placement day provenance',placement,V.validPlacement018,q=>q.placementDay++);
const discounted=structuredClone(payments[0]);discounted.quote.cost=1015.3125;discounted.capital[0].cost=1015;assert(V.validCapital018(discounted.id,discounted.quote,discounted.capital,20));negative('unrounded capital quote',discounted,q=>V.validCapital018(q.id,q.quote,q.capital,20),q=>q.capital[0].cost=1015.3125);
const families=[['streetscape015','__streetscapeQA015',8,'streetscapeAt015','british015','turn015'],['gardenLife016','__gardenLifeQA016',6,'gardenLifeAt016','british016','turn016'],['quayside017','__quaysideQA017',6,'quaysideAt017','british017','turn017']],fixtures=families.map(([family,key,count,get,themeKey,turnKey],side)=>{const paths=Array.from({length:count},(_,n)=>({x:5+n+side*20,y:68,theme:family+n,turn:n%4,cost:12}));return{family,key,count,get,themeKey,turnKey,paths,rows:paths.map(p=>({root:p.y*72+p.x,x:p.x,y:p.y,theme:p.theme,am502:1,amx502:{[themeKey]:p.theme,[turnKey]:p.turn},baseWalkCost:.72,cost:12,lighting:{ready:false}}))};});
const prior=functions018.find(f=>f.name==='waterfrontPriorPaths018').toString();assert(!/Evidence01[567]|forceDraw|step\(|ensure|rebuild|MarkDirty|dispatch|localStorage/.test(prior));
function observe(q){const before=JSON.stringify(q),reads=[],window={},GV={};for(const f of q){window[f.key]={paths:f.paths};GV[f.get]=(x,y)=>{reads.push([f.family,x,y]);return f.rows.find(r=>r.x===x&&r.y===y)||null;};}const result=new vm.Script('('+prior+')()').runInNewContext({window,GV});assert.equal(JSON.stringify(q),before);return{result:JSON.parse(JSON.stringify(result)),reads};}
const observed=observe(fixtures);assert.equal(observed.reads.length,20);assert(V.samePrior018(observed.result,[...observed.result].reverse()));
for(let side=0;side<3;side++)for(const[name,edit]of[['missing coordinate',f=>f.paths.pop()],['duplicate coordinate',f=>f.paths[1]={...f.paths[0],theme:f.paths[1].theme}],['missing native path',f=>f.rows.pop()],['saved direction changed',f=>f.rows[0].amx502[f.turnKey]++],['wrong native cost',f=>f.rows[0].cost++],['wrong native root',f=>f.rows[0].root++],['wrong path type',f=>f.rows[0].am502=2]]){const q=structuredClone(fixtures);edit(q[side]);assert.throws(()=>observe(q));rejected.push(families[side][0]+' '+name);}
for(const field of['family','root','x','y','theme','am502','cost','baseWalkCost','amx502'])negative('prior exact '+field,observed.result,q=>V.samePrior018(observed.result,q),q=>q[0][field]='changed');
const snap=functions018.filter(f=>['waterfrontState018','waterfrontStep018','waterfrontCapacity018','waterfrontIdentity018','waterfrontPriorPaths018'].includes(f.name)).map(f=>f.toString()).join('\n');assert(!/\b(?:ensure|rebuild|refresh|prepare|dispatch|testAge|innovationSetQA|setDay)[A-Za-z0-9_]*\s*\(/.test(snap));assert(!/\.age\s*=(?!=)|\.pw\s*=|\.wa\s*=|forceDraw|GV\.load|setItem/.test(snap));
const runner=fs.readFileSync(path.join(__dirname,'waterfront-integration-qa018.js'),'utf8');new vm.Script(runner);assert(runner.includes("process.env.GITHUB_ACTIONS!=='true'"));assert(runner.includes("head!==process.env.GITHUB_SHA"));assert(runner.includes("await cdp.send('Page.reload'"));assert(runner.includes("b.click();GV.setSpeed(0);GV.ai(false);return window.__waterfrontFns018.waterfrontState018()"));assert(runner.includes('requestAnimationFrame(()=>requestAnimationFrame('));assert(runner.includes('day<=3'));assert(runner.includes('iteration<=2'));
const cold=runner.slice(runner.indexOf("  if(MODE==='coldload'){"),runner.indexOf('  report.finalAssets='));assert(!/testAge|innovationSetQA|forceDraw|waterfrontDecodeInput018|waterfrontCatalog018|\.pw\s*=|\.wa\s*=/.test(cold));assert(cold.indexOf('for(let day=1;day<=3')<cold.lastIndexOf("call('waterfrontScene018'"));
const decode=functions018.find(f=>f.name==='waterfrontDecodeInput018');assert.deepEqual(decode(JSON.stringify({z:1,ter:'*4,2*4,0',tre:'*8,0',waterfront018:[[1,'lifeboatHall']]})),{ter:'22220000',tre:'00000000',waterfront018:[[1,'lifeboatHall']]});
console.log(JSON.stringify({ok:true,sourceOnly:true,syntheticDataOnly:true,gameExecuted:false,artExecuted:false,functions: functions018.length,directPriorCoordinates:20,coldReloadsRequired:2,unaidedDaysPerReload:3,allFourReferenceTransactionsRequired:true,rejected},null,2));
