'use strict';
// Inert source and synthetic transaction/geometry data only, never a game/painter.
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),{functions019,quarterCapitalNative019}=require('./waterfront-quarter-native019'),L=require('./waterfront-quarter-logic019');
for(const f of functions019)new vm.Script('('+f.toString()+')');let positives=0,negatives=0;
for(const length of[0,1,78,79,80])for(const id of['lifeboatHeritageHall018','canalTollhouseExhibit018']){
 const quote={tool:id,x:59,y:51,cost:1015.3125},before=Array.from({length},(_,n)=>({d:n,tool:'park',x:n%72,y:3,cost:60,k:4})),row={d:90,tool:id,x:59,y:51,cost:1015,k:287},after=[...before,row].slice(-80);assert(quarterCapitalNative019(id,quote,before,after,90));positives++;
 for(const mutate of[q=>q.pop(),q=>q.push({...row}),q=>q.at(-1).cost++,q=>q.at(-1).tool='footpath502',q=>q.at(-1).k=4,q=>q.at(-1).d++,q=>q.at(-1).x++,q=>q.at(-1).extra=true]){const bad=structuredClone(after);mutate(bad);assert(!quarterCapitalNative019(id,quote,before,bad,90));negatives++;}
 if(after.length>1){const bad=structuredClone(after);bad[0].cost++;assert(!quarterCapitalNative019(id,quote,before,bad,90));negatives++;}
}
const g=L.graph([{i:11,passable:true,flat:true,open:15,elevation:0},{i:12,passable:true,flat:true,open:15,elevation:1}],10);assert.equal(g.nodes.get(11).visual.length,0);assert.equal(g.nodes.get(11).mask,0);assert.equal(g.nodes.get(11).neighbors.length,1);
const native=fs.readFileSync('waterfront-quarter-native019.js','utf8'),game=fs.readFileSync('gameplay019.js','utf8'),runner=fs.readFileSync('probe-waterfront-quarter019.js','utf8'),preflight=fs.readFileSync('waterfront-quarter-preflight019.js','utf8');for(const [name,source]of Object.entries({native,game,runner,preflight}))new vm.Script(source,{filename:name});
const observation=functions019.filter(f=>['quarterIdentityNative019','quarterStateNative019','quarterStepNative019'].includes(f.name)).map(f=>f.toString()).join('\n');assert(!/\b(?:ensure|rebuild|refresh|dispatch|prepare|testAge|innovationSetQA)[A-Za-z0-9_]*\s*\(/.test(observation));assert(!/\.age\s*=(?!=)|\.pw\s*=|\.wa\s*=|GV\.forceDraw\(|localStorage\.setItem/.test(observation));
for(const feature of['GV.placeUndo','GV.placePreview459','GV.undo','GV.redo','capitalBefore','capitalAfter',"P.pay('tdig'",'quarterCapitalNative019','WALK_COST502','amVersion502','quarterTurn019'])assert((native+game).includes(feature),feature);
assert(game.includes('quarterFloorCache019.size>=128'));assert(game.includes('quarterRouteCache019.size>=64'));assert(game.includes('quarterStats019.visitors<24'));assert(game.includes('if(amDirty502||'));assert(!/Math\.random|\blocalStorage\b|\bsessionStorage\b/.test(game));
assert(runner.includes("process.env.GITHUB_ACTIONS!=='true'"));assert(preflight.includes("process.env.GITHUB_ACTIONS!=='true'"));assert(runner.includes('head!==process.env.GITHUB_SHA'));assert(runner.includes("await cdp.send('Page.reload'"));assert(runner.includes('iteration<=2'));assert(runner.includes('n<=3'));assert(runner.includes('Input.dispatchTouchEvent'));assert(runner.includes("type:'touchMove'"));assert(runner.includes('maxTouchPoints:2'));assert(runner.includes('[[390,844],[844,390]]'));assert(runner.includes('if(!ok)?')===false);
const cold=runner.slice(runner.indexOf("  if(MODE==='coldload'){"),runner.indexOf("  if(MODE==='mobile'){"));assert(!/testAge|innovationSetQA|ensure|rebuild|refresh|\.pw\s*=|\.wa\s*=/.test(cold));assert(cold.indexOf('for(let n=1;n<=3')<cold.indexOf("await shot('cold-'"));
// Validate the source-declared district geometry independently of the renderer.
const points=[],add=(theme,x,y)=>points.push({theme,x,y});for(const x of[59,60,65,66])add('arrivalCourt',x,54);for(const y of[55,60])for(let x=58;x<=69;x++)add('brickPromenade',x,y);for(const x of[60,66])for(let y=56;y<=59;y++)add('brickPromenade',x,y);for(const x of[61,62,63,64,65])add('arrivalCourt',x,57);for(const[x,y]of[[58,54],[62,54],[68,54]])add('harbourLantern',x,y);for(const[x,y]of[[59,56],[65,56]])add('heritageDisplay',x,y);for(const[x,y]of[[61,56],[67,56],[59,59],[67,59]])add('watersideBench',x,y);for(const[x,y]of[[62,58],[64,58]])add('timberShelter',x,y);for(let x=58;x<=69;x++)add(x===58||x===69?'quayCorner':'quayEdgeWalk',x,61);
assert.equal(points.length,64);assert.equal(new Set(points.map(p=>p.x+','+p.y)).size,64);for(const[x,y]of[[58,58],[58,59],[62,59],[64,59],[68,58],[68,59]])assert(!points.some(p=>p.x===x&&p.y===y));
const rows=points.map(p=>({i:p.y*72+p.x,theme:p.theme,flat:L.FLAT.includes(p.theme),passable:true,open:p.y===61?11:15}));for(const x of[59,60,65,66])rows.push({i:53*72+x,flat:true,passable:true,open:15});const graph=L.graph(rows,72);for(const x of[59,65]){const r=L.routes({x,y:51,sz:2,turn:0},graph);assert.equal(r.entry.connected.length,2);assert.equal(r.paths.length,4);for(const p of r.paths)assert(p.length<=13);}
const disconnected=L.graph(rows.filter(p=>![54*72+59,54*72+60].includes(p.i)),72);assert.equal(L.routes({x:59,y:51,sz:2,turn:0},disconnected).paths.length,0);assert(L.routes({x:65,y:51,sz:2,turn:0},disconnected).paths.length>0);
console.log(JSON.stringify({ok:true,sourceOnly:true,gameOrPainterExecuted:false,functions: functions019.length,capitalPositive:positives,capitalNegative:negatives,layoutCells:64,connectedHalls:2,newRuntimeModes:8}));
