/* Source-independent geometry/data checks. This file never loads the game/art. */
'use strict';
const assert=require('node:assert/strict'),L=require('./waterfront-quarter-logic019');let count=0;
const check=(name,f)=>{f();count++;},row=(x,y,n=12,extra={})=>({i:y*n+x,passable:true,flat:true,open:15,theme:'brickPromenade',...extra});
check('strict metadata rejects malformed and inherited data',()=>{
 for(const theme of L.THEMES)for(let turn=0;turn<4;turn++)assert.deepEqual(L.metadata({british019:theme,turn019:turn}),{theme,turn});
 for(const raw of [null,[],{}, {british019:'x',turn019:0},{british019:'arrivalCourt',turn019:4},{british019:'arrivalCourt',turn019:-1},{british019:'arrivalCourt',turn019:1.2},{british019:'arrivalCourt',turn019:'0'},{british019:'arrivalCourt',turn019:0,x:1},Object.create({british019:'arrivalCourt',turn019:0})])assert.equal(L.metadata(raw),null);
});
check('all16 masks rotate reversibly through four directions',()=>{for(let mask=0;mask<16;mask++)for(let turn=-8;turn<9;turn++){const r=L.rotateMask(mask,turn);assert.equal(L.rotateMask(r,-turn),mask);assert.equal(L.rotateMask(mask,turn+4),r);}assert.equal(L.rotateMask(1,1),2);assert.equal(L.rotateMask(7,1),14);for(const mask of[-1,16,NaN,1.5])assert.throws(()=>L.rotateMask(mask,1));});
check('diagonal, gap, water and map wrap never become edges',()=>{const g=L.graph([row(0,0),row(1,1),row(11,0),row(0,1,{})].slice(0,3),12);for(const n of g.nodes.values())assert.equal(n.visual.length,0);const h=L.graph([row(1,1),row(2,1,12,{passable:false}),row(3,1)],12);assert.equal(h.nodes.size,2);assert.equal(h.nodes.get(13).visual.length,0);});
check('physical closed sides require reciprocal connectivity',()=>{for(let d=0;d<4;d++){const [dx,dy]=L.DIRS[d],a=row(5,5,12,{open:15^(1<<d)}),b=row(5+dx,5+dy);const g=L.graph([a,b],12);assert.equal(g.nodes.get(a.i).neighbors.length,1);assert.equal(g.nodes.get(a.i).visual.length,0);assert.equal(g.nodes.get(a.i).mask,0);assert.equal(g.nodes.get(b.i).mask,0);}});
check('furniture remains native adjacent but visitors never enter it',()=>{const g=L.graph([row(2,2),row(3,2,12,{flat:false,theme:'timberShelter'})],12);assert.deepEqual(g.nodes.get(26).neighbors,[27]);assert.equal(g.nodes.get(26).mask,2);assert.equal(g.nodes.get(26).visual.length,0);assert.equal(L.position([26,27],g,0),null);});
check('front entrance follows all saved directions',()=>{const cells=[];for(let y=0;y<12;y++)for(let x=0;x<12;x++)if(x<4||x>5||y<4||y>5)cells.push(row(x,y));const g=L.graph(cells,12),expected=[[6*12+5,6*12+4],[5*12+3,4*12+3],[3*12+4,3*12+5],[4*12+6,5*12+6]];for(let turn=0;turn<4;turn++){const e=L.entrance({x:4,y:4,sz:2,turn},g);assert.equal(e.front,(turn+2)%4);assert.deepEqual(e.connected,expected[turn]);}});
check('invalid/outside hall and isolated front fail closed',()=>{const g=L.graph([row(4,6)],12);for(const hall of[{x:-1,y:4,sz:2,turn:0},{x:11,y:4,sz:2,turn:0},{x:4,y:4,sz:1,turn:0},{x:4,y:4,sz:2,turn:9}])assert.equal(L.entrance(hall,g).reason,'invalid-hall');assert.equal(L.entrance({x:4,y:4,sz:2,turn:0},g).reason,'front-path-missing');});
const cells=[];for(let y=6;y<12;y++)for(let x=0;x<12;x++)cells.push(row(x,y));const saved=JSON.stringify(cells),g=L.graph(cells,12),hall={x:4,y:4,sz:2,turn:0};
check('BFS bounds hold across route and visit limits',()=>{for(const maxVisited of[1,2,3,5,16,64,128,256])for(const maxDepth of[1,2,12,24])for(const maxRoutes of[0,1,4,8]){const r=L.routes(hall,g,{maxVisited,maxDepth,maxRoutes});assert(r.visited<=maxVisited);assert(r.paths.length<=maxRoutes);for(const p of r.paths){assert(p.length<=maxDepth+1);assert(r.entry.connected.includes(p[0]));assert(new Set(p).size===p.length);for(let i=1;i<p.length;i++)assert(g.nodes.get(p[i-1]).visual.includes(p[i]));}}});
check('invalid limits rejected',()=>{for(const opts of[{maxVisited:0},{maxVisited:257},{maxDepth:25},{maxDepth:0},{maxRoutes:9},{maxRoutes:-1}])assert.throws(()=>L.routes(hall,g,opts));});
check('position remains on actual horizontal/vertical segments for all times',()=>{const r=L.routes(hall,g);assert.equal(r.paths.length,4);for(const path of r.paths)for(let i=-500;i<1000;i++){const p=L.position(path,g,i/7,123);assert(p);const a=g.nodes.get(p.from),b=g.nodes.get(p.to);assert(p.fraction>=0&&p.fraction<=1);assert.equal(p.x,a.x+(b.x-a.x)*p.fraction);assert.equal(p.y,a.y+(b.y-a.y)*p.fraction);assert(a.i===b.i||a.visual.includes(b.i));}assert.equal(L.position(r.paths[0],g,Infinity),null);assert.equal(L.position([],g,0),null);});
check('pause and same time produce stable visual positions',()=>{const p=L.routes(hall,g).paths[0],states=new Set();for(let t=0;t<300;t+=.1){const a=L.position(p,g,t,7);assert.deepEqual(a,L.position(p,g,t,7));states.add(a.state);}assert.deepEqual([...states].sort(),['looking','waiting','walking']);});
check('activity respects real native state and weather/cull gates',()=>{const q={built:true,operational:true,employed:2,leisure:25};assert.equal(L.activity(q),4);assert.equal(L.activity({...q,night:true}),1);assert.equal(L.activity({...q,wet:true}),1);assert.equal(L.activity({...q,winter:true}),1);assert.equal(L.activity({...q,night:true,wet:true}),0);for(const extra of[{built:false},{built:1},{operational:false},{operational:1},{employed:0},{employed:NaN},{leisure:0},{zoom:.99},{disabled:true}])assert.equal(L.activity({...q,...extra}),0);});
check('zero RNG and no input mutation',()=>{const original=Math.random;Math.random=()=>{throw Error('RNG touched');};try{L.routes(hall,g);L.position(L.routes(hall,g).paths[0],g,55,5);L.activity({built:true,operational:true,employed:1,leisure:1});}finally{Math.random=original;}assert.equal(JSON.stringify(cells),saved);});
check('invalid or duplicate inventory rejected even nonpassable',()=>{for(const rows of[[row(0,0),row(0,0)], [row(0,0,12,{passable:false}),row(0,0)], [{i:-1,open:15}],[{i:144,open:15}],[{i:0,open:16}]])assert.throws(()=>L.graph(rows,12));});
console.log(JSON.stringify({ok:true,dataGroups:count,gameOrPainterExecuted:false}));
