'use strict';
// Synthetic JSON only; no browser or game execution.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),{createRequire}=require('node:module');
const ROOT=path.resolve(process.env.EXPECTED_RELEASE_ROOT||'../glimmer-waterfront018'),V=require(path.join(ROOT,'waterfront-lifecycle-contract018.js')),old=require(path.join(ROOT,'complexes-gameplay014.js')),S=require('./waterfront-public-new018');
const original=fs.readFileSync(path.join(__dirname,'retained017/quayside-public-mock-data017.js'),'utf8').replaceAll('./quayside-public-contract017','./waterfront-public-contract018').replaceAll('14.34','14.35'),m={exports:{}};new vm.Script('(function(require,module,exports){'+original+'\n})').runInThisContext()(createRequire(path.join(__dirname,'waterfront-public-lifecycle018.test.js')),m,m.exports);
let checks=0;const check=(name,fn)=>{fn();checks++;};
function good(day=0){
 const q=m.exports.goodQuayside();q.stats.day+=day;q.theatre.day=q.stats.day;const roots=[0,1,2].map(n=>{const x=63+n*3,y=64,root=y*72+x,v=n%4,theme=V.THEMES[n],age=9+day,bld={k:287,lv:1,v,sz:2,age,...(theme?{waterfront018:theme}:{})},native={root,k:287,sz:2,v,age,built:true,operational:true,powerState:1,waterState:{code:4},waterDelivered:1.8,road:[root-72],positions:5,employed:5,activity:{work:5,publicJobs:5,leisure:70,education:0,services:0},upkeep:3};q.cells.push({i:root,k:287,ref:null,sz:2,lv:1,v,age});for(let j=1;j<4;j++)q.cells.push({i:root+(j%2)+Math.floor(j/2)*72,k:287,ref:[x,y],sz:1,lv:null,v:null,age:null});return{id:V.IDS[n],theme,x,y,root,appearance:theme?{theme,root,v}:null,native,cells:[{bld},...[1,2,3].map(()=>({bld:{k:287,ref:[x,y]}}))]};});
 const before=structuredClone(q.complex.roots);q.complex.roots.push(...roots.map(r=>r.native));q.stats.buildings=q.cells.length;q.otherSlots={s1:'native1',s2:'native2',s1_bak:'native1bak',s2_bak:'native2bak'};
 const prior=[...q.streetscapeThemes.map(p=>({...p.at,family:'streetscape015'})),...q.gardenThemes.map(p=>({...p.at,family:'gardenLife016'})),...q.quaysideThemes.map(p=>({...p.at,family:'quayside017'}))];
 return{public:q,native:{day:q.stats.day,stats:structuredClone(q.stats),slot:'3',old:{roots:before},roots,prior,otherSlots:structuredClone(q.otherSlots),identity:{tags:roots.filter(r=>r.theme).map(r=>({root:r.root,k:287,ref:null,appearance:r.theme})),paths:q.paths,terrain:q.water,trees:[[100,1],[101,2]]}},disabled:false,artDisabled:false,edgeDisabled:false};
}
check('complete native heritage and old public world synthetic state passes',()=>assert.equal(S.validHeritageState018(good(),V,old),true));
for(const[name,change]of[['no heritage',q=>q.native.roots.pop()],['unpowered heritage',q=>q.native.roots[0].native.powerState=0],['no water heritage',q=>q.native.roots[0].native.waterDelivered=0],['unemployed heritage',q=>q.native.roots[0].native.employed=0],['missing heritage road',q=>q.native.roots[0].native.road=[]],['plain court tagged',q=>q.native.roots[2].cells[0].bld.waterfront018='lifeboatHall'],['wrong tagged reference',q=>q.native.roots[0].cells[1].bld.waterfront018='lifeboatHall'],['old native root lost',q=>q.native.old.roots.pop()],['old native root unpowered',q=>q.native.old.roots[0].powerState=0],['old native staff lost',q=>q.native.old.roots[0].employed=0],['old theatre unpowered',q=>q.public.theatre.roots[0].power=false],['old retained building lost',q=>q.public.retained.pop()],['old station track lost',q=>q.public.stations[0].ownedRail.pop()],['prior theme lost',q=>q.public.gardenThemes.pop()],['prior coordinate changed',q=>q.public.quaysideThemes[0].at.x++],['wrong version',q=>q.public.version='14.34'],['wrong slot',q=>q.native.slot='1'],['wrong day',q=>q.native.day++],['sandbox',q=>q.public.developer.sandbox=true],['god',q=>q.public.developer.god=true],['heritage escape',q=>q.disabled=true],['art escape',q=>q.artDisabled=true],['edge escape',q=>q.edgeDisabled=true]])check('functional public heritage rejects '+name,()=>{const q=good();change(q);assert.equal(S.validHeritageState018(q,V,old),false);});
check('all three ordinary days require exact native age progress and full owned identity',()=>{for(let d=0;d<=3;d++)assert.equal(S.sameHeritageIdentity018(good(),good(d),V,d),true);});
for(const[name,change]of[['wrong new direction',q=>q.native.roots[0].native.v++],['wrong new age',q=>q.native.roots[0].native.age++],['wrong tag',q=>q.native.identity.tags[0].appearance='canalTollhouse'],['wrong original reference',q=>q.public.cells.find(c=>c.ref).ref=[1,1]],['missing original cell',q=>q.public.cells.splice(0,1)],['prior direction changed',q=>q.native.prior[0].amx502.turn015=3],['prior paid cost changed',q=>q.native.prior[0].cost=0],['actual old theme changed',q=>q.public.streetscapeThemes[0].at.amx502.turn015=3],['other slot native changed',q=>q.native.otherSlots.s1='changed'],['other slot public changed',q=>q.public.otherSlots.s1='changed'],['water changed',q=>q.public.water[0].t=1],['paths changed',q=>q.native.identity.paths=[{}]],['terrain changed',q=>q.native.identity.terrain=[{}]],['tree lost',q=>q.native.identity.trees.pop()],['tree added',q=>q.native.identity.trees.push([102,1])],['tree kind changed',q=>q.native.identity.trees[0][1]=3]])check('cold world identity rejects '+name,()=>{const q=good();change(q);assert.equal(S.sameHeritageIdentity018(good(),q,V),false);});
const complete=()=>({checks:Array.from({length:35},(_,n)=>({scope:'waterfront',name:'synthetic heritage '+n,ok:true})),waterfrontChecksPassed:true,waterfrontColdReloads:[1,2].map(cycle=>({cycle,before:good(),immediate:good(),pausedFrames:[good(),good()],days:[1,2,3].map(day=>({ok:true,state:good(day)}))}))});
check('heritage summary requires all35 gates both cycles two paused frames and six individual days',()=>assert.equal(S.summarizeWaterfront018(complete(),V,old).passed,true));
for(const[name,change]of[['missing gate',r=>r.checks.pop()],['failed gate',r=>r.checks[0].ok=false],['extra gate',r=>r.checks.push(r.checks[0])],['wrong scope',r=>r.checks[0].scope='functional'],['missing completion',r=>r.waterfrontChecksPassed=false],['missing cycle',r=>r.waterfrontColdReloads.pop()],['swapped cycles',r=>r.waterfrontColdReloads.reverse()],['missing immediate',r=>delete r.waterfrontColdReloads[0].immediate],['missing paused frame',r=>r.waterfrontColdReloads[0].pausedFrames.pop()],['wrong paused identity',r=>r.waterfrontColdReloads[0].pausedFrames[0].native.identity.tags.pop()],['missing day',r=>r.waterfrontColdReloads[0].days.pop()],['first day failed',r=>r.waterfrontColdReloads[0].days[0].ok=false],['second day failed',r=>r.waterfrontColdReloads[0].days[1].ok=false],['third day failed',r=>r.waterfrontColdReloads[1].days[2].ok=false],['wrong day age',r=>r.waterfrontColdReloads[0].days[0].state.native.roots[0].native.age=11],['old public service lost',r=>r.waterfrontColdReloads[1].days[0].state.public.theatre.roots[0].power=false]])check('heritage summary rejects '+name,()=>{const r=complete();change(r);assert.equal(S.summarizeWaterfront018(r,V,old).passed,false);});
const edge=()=>({checks:Array.from({length:42},()=>({scope:'mapedge',ok:true})),waterfrontMapedgePassed:true,waterfrontMapedge:{surveys:Array(4).fill({}),pairs:Array(36).fill({})}});
check('edge summary requires all42 gates four rotations and36 native pairs',()=>assert.equal(S.summarizeMapedge018(edge()).passed,true));for(const[name,change]of[['gate lost',r=>r.checks.pop()],['gate failed',r=>r.checks[0].ok=false],['rotation lost',r=>r.waterfrontMapedge.surveys.pop()],['pair lost',r=>r.waterfrontMapedge.pairs.pop()],['no completion',r=>r.waterfrontMapedgePassed=false]])check('edge summary rejects '+name,()=>{const r=edge();change(r);assert.equal(S.summarizeMapedge018(r).passed,false);});
console.log(JSON.stringify({ok:true,sourceOnly:true,gameExecuted:false,checks,expectedHeritageGates:35,expectedMapedgeGates:42}));
